name: flutterdemo
description: fingertips webview demo

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  webview_flutter: ^0.3.22+1
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/demo.html
    - assets/web/
    - assets/web/images/
    - assets/web/images/close.svg
    - assets/web/images/tick.svg
    - assets/web/fonts/
    - assets/web/fonts/nunito-v12-latin-700.woff
    - assets/web/fonts/nunito-v12-latin-regular.woff
    - assets/web/fonts/nunito-v12-latin-600.woff
    - assets/web/js/
    - assets/web/js/question.js
    - assets/web/question_explanation.html
    - assets/web/question.html
    - assets/web/css/
    - assets/web/css/question.css
    - assets/web/MathJax/
    - assets/web/MathJax/extensions/
    - assets/web/MathJax/extensions/MathZoom.js
    - assets/web/MathJax/extensions/TeX/
    - assets/web/MathJax/extensions/TeX/AMSmath.js
    - assets/web/MathJax/extensions/TeX/enclose.js
    - assets/web/MathJax/extensions/TeX/verb.js
    - assets/web/MathJax/extensions/TeX/extpfeil.js
    - assets/web/MathJax/extensions/TeX/cancel.js
    - assets/web/MathJax/extensions/TeX/color.js
    - assets/web/MathJax/extensions/TeX/unicode.js
    - assets/web/MathJax/extensions/TeX/mathchoice.js
    - assets/web/MathJax/extensions/TeX/newcommand.js
    - assets/web/MathJax/extensions/TeX/noUndefined.js
    - assets/web/MathJax/extensions/TeX/AMScd.js
    - assets/web/MathJax/extensions/TeX/noErrors.js
    - assets/web/MathJax/extensions/TeX/boldsymbol.js
    - assets/web/MathJax/extensions/TeX/autobold.js
    - assets/web/MathJax/extensions/TeX/action.js
    - assets/web/MathJax/extensions/TeX/mediawiki-texvc.js
    - assets/web/MathJax/extensions/TeX/begingroup.js
    - assets/web/MathJax/extensions/TeX/mhchem.js
    - assets/web/MathJax/extensions/TeX/autoload-all.js
    - assets/web/MathJax/extensions/TeX/HTML.js
    - assets/web/MathJax/extensions/TeX/bbox.js
    - assets/web/MathJax/extensions/TeX/AMSsymbols.js
    - assets/web/MathJax/extensions/MathEvents.js
    - assets/web/MathJax/extensions/MathML/
    - assets/web/MathJax/extensions/MathML/mml3.js
    - assets/web/MathJax/extensions/MathML/content-mathml.js
    - assets/web/MathJax/extensions/FontWarnings.js
    - assets/web/MathJax/extensions/HTML-CSS/
    - assets/web/MathJax/extensions/HTML-CSS/handle-floats.js
    - assets/web/MathJax/extensions/Safe.js
    - assets/web/MathJax/extensions/CHTML-preview.js
    - assets/web/MathJax/extensions/mml2jax.js
    - assets/web/MathJax/extensions/tex2jax.js
    - assets/web/MathJax/extensions/jsMath2jax.js
    - assets/web/MathJax/extensions/toMathML.js
    - assets/web/MathJax/extensions/HelpDialog.js
    - assets/web/MathJax/extensions/MatchWebFonts.js
    - assets/web/MathJax/extensions/asciimath2jax.js
    - assets/web/MathJax/jax/
    - assets/web/MathJax/jax/input/
    - assets/web/MathJax/jax/input/TeX/
    - assets/web/MathJax/jax/input/TeX/config.js
    - assets/web/MathJax/jax/input/TeX/jax.js
    - assets/web/MathJax/jax/input/MathML/
    - assets/web/MathJax/jax/input/MathML/entities/
    - assets/web/MathJax/jax/input/MathML/entities/c.js
    - assets/web/MathJax/jax/input/MathML/entities/o.js
    - assets/web/MathJax/jax/input/MathML/entities/i.js
    - assets/web/MathJax/jax/input/MathML/entities/j.js
    - assets/web/MathJax/jax/input/MathML/entities/a.js
    - assets/web/MathJax/jax/input/MathML/entities/z.js
    - assets/web/MathJax/jax/input/MathML/entities/u.js
    - assets/web/MathJax/jax/input/MathML/entities/p.js
    - assets/web/MathJax/jax/input/MathML/entities/x.js
    - assets/web/MathJax/jax/input/MathML/entities/g.js
    - assets/web/MathJax/jax/input/MathML/entities/n.js
    - assets/web/MathJax/jax/input/MathML/entities/y.js
    - assets/web/MathJax/jax/input/MathML/entities/e.js
    - assets/web/MathJax/jax/input/MathML/entities/l.js
    - assets/web/MathJax/jax/input/MathML/entities/scr.js
    - assets/web/MathJax/jax/input/MathML/entities/t.js
    - assets/web/MathJax/jax/input/MathML/entities/q.js
    - assets/web/MathJax/jax/input/MathML/entities/s.js
    - assets/web/MathJax/jax/input/MathML/entities/r.js
    - assets/web/MathJax/jax/input/MathML/entities/opf.js
    - assets/web/MathJax/jax/input/MathML/entities/w.js
    - assets/web/MathJax/jax/input/MathML/entities/h.js
    - assets/web/MathJax/jax/input/MathML/entities/k.js
    - assets/web/MathJax/jax/input/MathML/entities/f.js
    - assets/web/MathJax/jax/input/MathML/entities/v.js
    - assets/web/MathJax/jax/input/MathML/entities/fr.js
    - assets/web/MathJax/jax/input/MathML/entities/b.js
    - assets/web/MathJax/jax/input/MathML/entities/d.js
    - assets/web/MathJax/jax/input/MathML/entities/m.js
    - assets/web/MathJax/jax/input/MathML/config.js
    - assets/web/MathJax/jax/input/MathML/jax.js
    - assets/web/MathJax/jax/input/AsciiMath/
    - assets/web/MathJax/jax/input/AsciiMath/config.js
    - assets/web/MathJax/jax/input/AsciiMath/jax.js
    - assets/web/MathJax/jax/output/
    - assets/web/MathJax/jax/output/NativeMML/
    - assets/web/MathJax/jax/output/NativeMML/config.js
    - assets/web/MathJax/jax/output/NativeMML/jax.js
    - assets/web/MathJax/jax/output/SVG/
    - assets/web/MathJax/jax/output/SVG/fonts/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Math/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Math/BoldItalic/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Math/BoldItalic/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Math/Italic/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Math/Italic/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size4/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size4/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size4/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Typewriter/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Typewriter/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Typewriter/Regular/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Typewriter/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Typewriter/Regular/Other.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Typewriter/Regular/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Bold/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Bold/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Bold/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Bold/Other.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Bold/PUA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Regular/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Regular/Other.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Fraktur/Regular/PUA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size2/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size2/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size2/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size1/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size1/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size1/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/fontdata-extra.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Italic/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Italic/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Italic/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Italic/Other.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Italic/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Bold/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Bold/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Bold/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Bold/Other.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Bold/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Regular/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Regular/Other.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/SansSerif/Regular/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/EnclosedAlphanum.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/Latin1Supplement.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/LetterlikeSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/MiscTechnical.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/MathOperators.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/BoxDrawing.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/MiscSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/Arrows.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/GreekAndCoptic.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/GeneralPunctuation.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/SpacingModLetters.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/LatinExtendedA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/MiscMathSymbolsB.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/Dingbats.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/PUA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/SuppMathOperators.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/AMS/Regular/GeometricShapes.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Caligraphic/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Caligraphic/Bold/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Caligraphic/Bold/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Caligraphic/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Caligraphic/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size3/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size3/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Size3/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Script/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Script/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Script/Regular/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Script/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/fontdata.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/LetterlikeSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/MathOperators.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/LatinExtendedB.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/GreekAndCoptic.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/GeneralPunctuation.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Italic/LatinExtendedA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/Latin1Supplement.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/LetterlikeSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/SupplementalArrowsA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/MiscTechnical.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/MathOperators.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/LatinExtendedB.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/MiscSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/MiscMathSymbolsA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/Arrows.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/GreekAndCoptic.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/GeneralPunctuation.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/SpacingModLetters.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/LatinExtendedA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/SuppMathOperators.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/CombDiactForSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Bold/GeometricShapes.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/LetterlikeSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/MathOperators.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/LatinExtendedB.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/BasicLatin.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/MiscSymbols.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/Main.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/GreekAndCoptic.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/SpacingModLetters.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/CombDiacritMarks.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/LatinExtendedA.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/SuppMathOperators.js
    - assets/web/MathJax/jax/output/SVG/fonts/TeX/Main/Regular/GeometricShapes.js
    - assets/web/MathJax/jax/output/SVG/autoload/
    - assets/web/MathJax/jax/output/SVG/autoload/annotation-xml.js
    - assets/web/MathJax/jax/output/SVG/autoload/menclose.js
    - assets/web/MathJax/jax/output/SVG/autoload/ms.js
    - assets/web/MathJax/jax/output/SVG/autoload/mglyph.js
    - assets/web/MathJax/jax/output/SVG/autoload/mtable.js
    - assets/web/MathJax/jax/output/SVG/autoload/multiline.js
    - assets/web/MathJax/jax/output/SVG/autoload/maction.js
    - assets/web/MathJax/jax/output/SVG/autoload/mmultiscripts.js
    - assets/web/MathJax/jax/output/SVG/config.js
    - assets/web/MathJax/jax/output/SVG/jax.js
    - assets/web/MathJax/jax/output/CommonHTML/
    - assets/web/MathJax/jax/output/CommonHTML/config.js
    - assets/web/MathJax/jax/output/CommonHTML/jax.js
    - assets/web/MathJax/jax/element/
    - assets/web/MathJax/jax/element/mml/
    - assets/web/MathJax/jax/element/mml/optable/
    - assets/web/MathJax/jax/element/mml/optable/Latin1Supplement.js
    - assets/web/MathJax/jax/element/mml/optable/LetterlikeSymbols.js
    - assets/web/MathJax/jax/element/mml/optable/SupplementalArrowsA.js
    - assets/web/MathJax/jax/element/mml/optable/MiscTechnical.js
    - assets/web/MathJax/jax/element/mml/optable/MathOperators.js
    - assets/web/MathJax/jax/element/mml/optable/BasicLatin.js
    - assets/web/MathJax/jax/element/mml/optable/MiscMathSymbolsA.js
    - assets/web/MathJax/jax/element/mml/optable/Arrows.js
    - assets/web/MathJax/jax/element/mml/optable/GreekAndCoptic.js
    - assets/web/MathJax/jax/element/mml/optable/GeneralPunctuation.js
    - assets/web/MathJax/jax/element/mml/optable/SpacingModLetters.js
    - assets/web/MathJax/jax/element/mml/optable/CombDiacritMarks.js
    - assets/web/MathJax/jax/element/mml/optable/MiscMathSymbolsB.js
    - assets/web/MathJax/jax/element/mml/optable/Dingbats.js
    - assets/web/MathJax/jax/element/mml/optable/SuppMathOperators.js
    - assets/web/MathJax/jax/element/mml/optable/CombDiactForSymbols.js
    - assets/web/MathJax/jax/element/mml/optable/SupplementalArrowsB.js
    - assets/web/MathJax/jax/element/mml/optable/MiscSymbolsAndArrows.js
    - assets/web/MathJax/jax/element/mml/optable/GeometricShapes.js
    - assets/web/MathJax/jax/element/mml/jax.js
    - assets/web/MathJax/MathJax.js
    - assets/web/MathJax/config/
    - assets/web/MathJax/config/TeX-AMS-MML_HTMLorMML.js
    - assets/web/MathJax/config/local/
    - assets/web/MathJax/config/local/local.js
    - assets/web/MathJax/config/TeX-AMS-MML_SVG.js

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
